### ISSUE TITLE
protoc-gen-nexus 0.6.4 is empty

### ISSUE THREAD

**Issue by qnighy** [proto-graphql/proto-graphql-js#300]
As witnessed by the diff below, protoc-gen-nexus 0.6.4 is devoid of the whole `./lib` things. Probably the build step was missed out before publishing.

https://app.renovatebot.com/package-diff?name=protoc-gen-nexus&from=0.6.2&to=0.6.4

@izumin5210

**Comment by izumin5210** [comment]
Fixed and re-released as 0.6.5 :bow: https://github.com/proto-graphql/proto-graphql-js/pull/309

**Comment by qnighy** [comment]
Looks nice, thanks! https://app.renovatebot.com/package-diff?name=protoc-gen-nexus&from=0.6.2&to=0.6.5
